(do (define fac (fun (n)
        (let fac_tailcall (fun (x acc)
            (? (> x 1)
                (fac_tailcall (- x 1) (* x acc))
            acc)   
        )
        (fac_tailcall n 1))
    ))
    (define fac_tail (fun (x acc)
        (? (> x 1)
            (fac_tail (- x 1) (* x acc))
            acc
        )
    ))
)